# Generated by Django 2.2.3 on 2019-07-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=100)),
                ('last_watched_season', models.IntegerField()),
                ('last_watched_series', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv_series.Status')),
            ],
        ),
    ]
