# Generated by Django 2.2.3 on 2019-07-04 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_watched_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
