# Generated by Django 2.2.3 on 2019-07-04 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0002_auto_20190704_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 4, 19, 4, 47, 673493, tzinfo=utc)),
        ),
    ]
