# Generated by Django 2.2.3 on 2019-07-04 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0004_auto_20190704_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
