# Generated by Django 2.2.3 on 2019-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0005_auto_20190704_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='local_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='original_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
