# Generated by Django 2.2.3 on 2019-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0006_auto_20190704_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_season',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_watched_series',
            field=models.IntegerField(null=True),
        ),
    ]
