# Generated by Django 2.2.3 on 2019-07-04 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0007_auto_20190704_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
