# Generated by Django 2.2.4 on 2019-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0009_auto_20191010_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_season',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_watched_series',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
