# Generated by Django 2.2.4 on 2019-10-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0010_auto_20191010_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='last_watched_season',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
