# Generated by Django 2.2.4 on 2019-10-10 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv_series', '0011_auto_20191010_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='local_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='journal',
            name='original_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('owner', 'original_name'), ('owner', 'local_name')},
        ),
    ]
