# Generated by Django 2.2.4 on 2019-10-10 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0012_auto_20191010_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_watched_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tv_series.Status'),
        ),
    ]
