# Generated by Django 2.2.4 on 2019-10-15 08:23

from django.db import migrations


def move_tv_series(apps, schema_editor):
    Journal = apps.get_model('tv_series', 'Journal')
    TVSeries = apps.get_model('tv_series', 'TVSeries')

    for journal in Journal.objects.all():
        try:
            tv_series = TVSeries.objects.get(local_name=journal.local_name, original_name=journal.original_name)
        except TVSeries.DoesNotExist:
            tv_series = TVSeries(owner=journal.owner, local_name=journal.local_name,
                                 original_name=journal.original_name)
            tv_series.save()
        journal.tv_series = tv_series
        journal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0017_auto_20191015_0823'),
    ]

    operations = [
        migrations.RunPython(move_tv_series)
    ]
