# Generated by Django 2.2.4 on 2019-10-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0018_auto_20191015_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='local_name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='original_name',
        ),
        migrations.AlterField(
            model_name='journal',
            name='tv_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv_series.TVSeries'),
        ),
    ]
