# Generated by Django 2.2.4 on 2019-10-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0019_auto_20191015_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='tv_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tv_series.TVSeries',
                                    verbose_name='TV series'),
        ),
    ]
