# Generated by Django 3.0.4 on 2020-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0021_auto_20200316_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Watching'), (2, 'Waiting'), (3, 'Done'), (4, 'Stopped'), (5, 'Didnt Watch')], default=5),
        ),
    ]
