# Generated by Django 3.0.4 on 2020-03-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0022_auto_20200319_0702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
