# Generated by Django 3.0.4 on 2020-03-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0023_delete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='last_watched_series',
            new_name='last_watched_episode',
        ),
    ]
