# Generated by Django 3.0.4 on 2020-03-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0024_auto_20200319_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'TV series entry', 'verbose_name_plural': 'TV series entries'},
        ),
        migrations.AlterModelOptions(
            name='tvseries',
            options={'verbose_name': 'TV series', 'verbose_name_plural': 'TV series'},
        ),
    ]
