version: '3'

services:
  app:
    container_name: tabular-notes
    build: .
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tabular-notes.local
    volumes:
      - ./data/db_prod.sqlite3:/app/data/db_prod.sqlite3