version: '3'

services:
  app:
    container_name: tabular-notes
    build: .
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - ./data/db_prod.sqlite3:/app/data/db_prod.sqlite3