version: '3'

services:
  app:
    container_name: tabular-notes-app
    build: .
    image: phpusr/tabular-notes
    restart: unless-stopped
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/app
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    ports:
      - ${PORT:-8002}:8000
    depends_on:
      - db

  db:
    container_name: tabular-notes-db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data