version: '3'

services:
  app:
    container_name: tabular-notes-app
    build: .
    image: phpusr/tabular-notes
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=FALSE
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/app
      - CELERY_BROKER_URL=redis://redis
    ports:
      - ${APP_PORT:-8002}:8000
    volumes:
      - ./data/celerybeat-schedule:/app/data/celerybeat-schedule
    depends_on:
      - db

  db:
    container_name: tabular-notes-db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
  
  redis:
    container_name: tabular-notes-redis
    image: redis:6.2
    restart: unless-stopped
