version: '3'

services:
  app:
    container_name: tabular-notes_app
    build: .
    restart: unless-stopped
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://tabular_notes:passw0rd@db:5432/tabular_notes
    depends_on:
      - db

  db:
    container_name: tabular-notes_db
    image: postgres:11.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: tabular_notes
      POSTGRES_PASSWORD: passw0rd
    ports:
      - 5433:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data