# Generated by Django 2.2.4 on 2019-10-11 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
