# Generated by Django 2.2.4 on 2019-10-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191011_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Source'),
        ),
    ]
