# Generated by Django 2.2.4 on 2019-10-11 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_auto_20191011_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('owner', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('owner', 'name')},
        ),
    ]
