# Generated by Django 2.2.4 on 2019-10-12 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20191012_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='add_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
