# Generated by Django 3.0.1 on 2020-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200316_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Didnt Read'), (2, 'Reading'), (3, 'Read'), (4, 'Stopped')], default=1),
        ),
    ]
