# Generated by Django 3.0.1 on 2020-03-16 13:07

from django.db import migrations


def change_book_reading_status(apps, schema_editor):
    Journal = apps.get_model('books', 'Journal')

    Journal.objects.filter(start_date__isnull=False, end_date__isnull=False).update(status=3)
    Journal.objects.filter(start_date__isnull=False, end_date__isnull=True).update(status=4)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_journal_status'),
    ]

    operations = [
        migrations.RunPython(change_book_reading_status)
    ]
