# Generated by Django 3.0.4 on 2020-03-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20200319_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Book entry', 'verbose_name_plural': 'Book entries'},
        ),
    ]
