# Generated by Django 3.2.16 on 2022-11-26 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_first_name_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_app_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
